### PR TITLE
Browser Readable Sitemap with XSLT

### PR DESCRIPTION
**Pull request by Jako**
At the moment it works only with not moved assets folder. The xsl file relies on assets/components/googlesitemap for css and images.

The xsl/css file comes from http://sourceforge.net/projects/gstoolbox/ and was slightly modernized.

### CODE REVIEW

**Comment by sepiariver** [comment]
@jako you want me to merge conflicts or do you want to? If you do it you'll get credit for the PR. The new snippet is quite different from old one. Old is now GoogleSiteMapVersion1 and is called by new one, with $scriptProperties. But the change in gContainer chunk should work with both if you use system config placeholder [[++assets_url]]

**Comment by Jako** [comment]
I could rebase my fork and create a new PR, if you want.

**Comment by sepiariver** [comment]
Then you would get credit for your work, so I think that's better. Otherwise it's me adding stuff from your fork—not as good.

**Comment by Jako** [comment]
Ok. I will create a PR.

**Pull request closed without merging**
